### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by asterite** [l3kn/stumpy_png#1]
Hi again!

First of all: this shard is awesome, thank you!!

I wanted to do this challenge: https://www.reddit.com/r/dailyprogrammer/comments/4v5h3u/20160729_challenge_277_hard_trippy_julia_fractals/

I did it, but then I needed to generate an image. I remembered seeing your project and I said "let's try it". I just had to read the "write" example from the README to make it work, and it worked out of the box, and it was super fast! I love it when that happens :-)

<details>
<summary>Here's the program, in case you want to try it (compile with `--release` because otherwise it's a very slow)</summary>
```cr
require "complex"
require "stumpy_png"

def f(z)
  z*z - 0.221 - 0.713.i
end

def compute(pix)
  i = 0
  loop do
    pix = f(pix)
    i += 1
    break if pix.abs >= 128
  end
  i
end

width = 1920
height = 1200

matrix = Array.new(width) { Array.new(height, 0) }
max = 0

width.times do |x|
  height.times do |y|
    cx = -1.0 + (2.0/(width - 1)) * x
    cy = -1.0 + (2.0/(height - 1)) * y
    value = compute(cx + cy.i)
    max = {max, value}.max
    matrix[x][y] = value
  end
end

canvas = StumpyPNG::Canvas.new(width, height)

width.times do |x|
  height.times do |y|
    value = matrix[x][y]
    value = value.fdiv(max)
    value = (255 * value).to_i
    color = StumpyPNG::RGBA.from_rgb_n({value, value, value}, 8)
    canvas.set_pixel(x, y, color)
  end
end

StumpyPNG.write(canvas, "output.png")
```
</details>

On my machine it takes 2s to generate a 1920x1200 image, which is not bad at all!

Then, as always, I wondered if this could be further optimized, so I started to look at the code and found several optimization opportunities. With some simple changes I was able to cut the time to 1s, and I'm sure I could even optimize it further.

Most of the changes will be transparent to the user, just how data is stored internally in some types. However, there is one change that already reduces the time from 2s to 1.5s: change RGBA from a class to a struct. Having one instance in heap memory for each pixel is pretty expensive. And I think RGBA is ideal for a struct, as its size is 64 bits, so a word nowadays. However, if we do that, I'd also make it immutable to prevent someone from taking an rgba instance and modifying it, only to find out a copy was modified. So one would have to take it, create a modified instance, and put it back. I think it's a good compromise if we want to speed up things, but I wanted to know your opinion before sending a big PR changing these things.

**Comment by l3kn** [comment]
Sorry that it took so long for me to answer this, for some reason the issue did not show up in my Github notifications :(

Currently I am only using this code in places where the performance isn't to relevant,
but I will try out your fractal program (and maybe some more big images).

I'm sure there are many are many areas that could be optimized
or done in a more elegant way.
Making RGBA a struct sounds like a good starting point
and I would gladly accept your PR.

**Comment by asterite** [comment]
@l3kn No worries at all :-)

I'll send a PR with a few changes, at least it will be about twice as fast.

A side question: yesterday at my workplace we were looking at your [raytracer](https://github.com/l3kn/raytracer-crystal) project with awe (and a bit of nostalgia :-)), and saw the time it takes to render the teapot: 41 minutes. Is that a reasonable time? I ask because neither of us knows what are reasonable times for this, but we read somewhere that the teapot is used for benchmarks as it's pretty "complex". I also profiles the program and all the time is spent on the "triangle hit" part, so there doesn't seem to be anything wrong with the implementation. Just out of curiosity :-)

**Comment by l3kn** [comment]
Thanks!

41 minutes is not reasonable at all,
I think at the time I ran that example
my `BVHNode` implementation was broken
(<https://en.wikipedia.org/wiki/Bounding_volume_hierarchy>
, it's like a binary search tree for (3D) objects).

Instead I used the `HitableList`class
where the hit function iterates over all objects
(in this case ~2500 triangles)
and stores the `Intersection` that is closest to the camera.

Using a `BVHNode` to store the triangles,
rendering now takes only 60s,
I guess I should update the scene and the readme ;)

PS:

If you are interested in writing your own raytracer,
my implementation is (loosely) based on
[Raytracing in one weekend](http://in1weekend.blogspot.de/2016/01/ray-tracing-in-one-weekend.html) which seems to be (even though the layout of the ebook could be better)
a good introduction to the topic and gets to a point where you can render some cool images pretty fast.
