### ISSUE TITLE
Change the "Reading usage" example to something more current

### ISSUE THREAD

**Issue by N0r1x** [l3kn/stumpy_png#12]
Hello, I am (trying to) use your library for a pet project in Crystal. As new to the language as I am, I copy pasted the `require "stumpy_png"` from the example in the README. Turns out, that wasn't a good idea. I fixed it by changing it to `require "stumpy_core"`. Maybe changing it to a more current/ noob-friendly out-of-the-box example wouldn't be a bad idea?

**Comment by N0r1x** [comment]
Nevermind, I had included stumpy_core in the shard.yml file.

**Comment by l3kn** [comment]
Thanks for the feedback, I'll add an example of how the `shard.yml` file should look like to the readme
