### ISSUE TITLE
Feature Request: Tinting 

### ISSUE THREAD

**Issue by redcodefinal** [l3kn/stumpy_png#6]
Hello @l3kn! Wanted to suggest a feature, maybe implement it myself with some guidance to see how you want this feature. Currently I am working on using this library to make pretty isometric worlds like [these](broken-kami.tumblr.com). Part of the process is recoloring pngs programmatically. From my understanding of how this feature should work, it would desaturate the png, then color it keeping it's value intact. Take a look at [this](http://66.media.tumblr.com/56b1c87699c7e0250e46393ffdd7fb08/tumblr_o8xwowftFs1uc8tiho2_1280.png) picture, then take a look at the [asset ](https://raw.githubusercontent.com/redcodefinal/isometric-world-generator/master/content/simple/blocks/block/base.png) behind it. I figured the implmentation would be tied to ```Canvas``` maybe in the definition ```Canvas#tint(color : RGBA)```. It would then go through desaturating the png and applying the color whilst preserving the value. Let me know if you have any suggestions on how I should do this, I'll be playing around with some ideas I have for completing this today.

**Comment by l3kn** [comment]
Those isometric worlds look very nice!

Give me a few minutes to think about this...

**Comment by redcodefinal** [comment]
One way to make this change easier would be to implement HSV conversion, something [I am familiar with] (https://github.com/redcodefinal/EntityEngineV4/blob/Development/EntityEngineV4/Data/Color.cs#L437) I wouldn't mind writing the extra colors in.

**Comment by l3kn** [comment]
A method like `StumpyCore::RGBA.from_hsv({h, s, v})` would be pretty nice to have.
I think I don't really understand what you mean by
„It would then go through desaturating the png and applying the color whilst preserving the value.“, are there specific equations for this?

Should the grey lines keep their color during this process?

By replacing just the white parts with some other color,
I get results like this:

![image](https://cloud.githubusercontent.com/assets/2060269/20199231/697eed46-a7a9-11e6-94de-23bf6eaecee2.png)

``` crystal
require "stumpy_png"
include StumpyPNG

world = Canvas.new(128, 128)
tile = StumpyPNG.read("base.png")

def replace(canvas : Canvas, old : RGBA, new : RGBA)
  new_canvas = Canvas.new(canvas.width, canvas.height)
  (0...canvas.width).each do |x|
    (0...canvas.height).each do |y|
      pixel = canvas[x, y]
      if pixel == old
        new_canvas[x, y] = new
      else
        new_canvas[x, y] = pixel
      end
    end
  end

  new_canvas
end

5.times do |i|
  5.times do |j|
    x = 31 * i
    y = 22 * j

    x -= 16 if j.odd?

    old_color = RGBA.from_rgb_n({255, 255, 255}, 8)
    new_color = RGBA.from_rgb_n({50*j, 50*i, 255}, 8)
    new_tile = replace(tile, old_color, new_color)
    world.paste(new_tile, x, y)
  end
end

StumpyPNG.write(world, "output.png")
```

**Comment by redcodefinal** [comment]
In the real use examples I gave you, I had added some extra shading/lighting. I would ignore it. It should change the grey lines to be a darker form of the tint color. I haven't finished writing a working tint method yet. Here is a better example, explained in the terms of a photo editor. Take a look at [this](http://imgur.com/a/yVV5n). The top image represents a tinted (red) image, versus the bottom which has been untinted. The bottom one is the bottom layer, the top one has a layer of solid red, blending mode turned to multiply above the original. This doesn't color pixels with alpha equal to 0, or full black, but does color any shade of white/grey, darkening it to the same darkness as the original pixel. My explanation of what is going on probably isn't the best because most times I have had to use this kind of feature, it was already built in for me (like Ruby's Gosu or C#'s XNA).

**Comment by l3kn** [comment]
``` crystal
require "stumpy_png"
include StumpyPNG

world = Canvas.new(128, 128)
tile = StumpyPNG.read("base.png")

def tint(canvas : Canvas, color : RGBA)
  r0 = color.r.to_f / UInt16::MAX
  g0 = color.g.to_f / UInt16::MAX
  b0 = color.b.to_f / UInt16::MAX
  new_canvas = Canvas.new(canvas.width, canvas.height)
  (0...canvas.width).each do |x|
    (0...canvas.height).each do |y|
      pixel = canvas[x, y]
      r1 = pixel.r.to_f / UInt16::MAX
      g1 = pixel.g.to_f / UInt16::MAX
      b1 = pixel.b.to_f / UInt16::MAX
      new_canvas[x, y] = RGBA.new(
        (r0 * r1 * UInt16::MAX).to_u16,
        (g0 * g1 * UInt16::MAX).to_u16,
        (b0 * b1 * UInt16::MAX).to_u16,
        pixel.a
      )
    end
  end

  new_canvas
end

5.times do |i|
  5.times do |j|
    x = 31 * i
    y = 22 * j

    x -= 16 if j.odd?

    new_color = RGBA.from_rgb_n({50*j, 50*i, 255}, 8)
    new_tile = tint(tile, new_color)
    world.paste(new_tile, x, y)
  end
end

StumpyPNG.write(world, "output.png")
```

![image](https://cloud.githubusercontent.com/assets/2060269/20200507/d95beefe-a7b1-11e6-9b2b-efdd8f4f8268.png)

This looks much better!

Over the weekend I'll try to implement some [Blend Modes](https://en.wikipedia.org/wiki/Blend_modes) for `RGBA`
and implement `Canvas.tint`.

If you want to help, feel free to open up a pull request :)

**Comment by redcodefinal** [comment]
Will do! I'll have some time this weekend. CODE JAM!

**Comment by l3kn** [comment]
I'll take a look at that gitter thing.

Your images got me interested
and hacked together something similar (hope you don't mind),
but using the Bresenham line-drawing algorithm, flood-filling and some weird z-buffer stuff.

![image](https://cloud.githubusercontent.com/assets/2060269/20202672/2e0c5290-a7c1-11e6-970c-c09d6e0f000e.png)
[code on github](https://github.com/l3kn/hacky_isometric)

Surprisingly kind of works 0.o,
even though there are some strange glitches.

The image-based approach you are using
is definitely more flexible and “stable”.

**Comment by redcodefinal** [comment]
Dope! Of course I don't mind!

**Comment by l3kn** [comment]
I created a gitter room at <https://gitter.im/stumpy_core>.

The `stumpy_core` repository now has a branch for these new features,
see [stumpy_core/blending-modes](https://github.com/l3kn/stumpy_core/tree/blending-modes).

Using the following dependencies in a `shard.yml` file

```yaml
dependencies:
  stumpy_core:
    github: l3kn/stumpy_core
    branch: blending-modes
  stumpy_png:
    github: l3kn/stumpy_png
    branch: master
```

the code snippet from above can be simplified to

``` crystal
require "stumpy_png"
require "stumpy_core"

include StumpyCore

world = Canvas.new(128, 128)
tile = StumpyPNG.read("base.png")

5.times do |i|
  5.times do |j|
    x = 31 * i
    y = 22 * j
    x -= 16 if j.odd?

    new_color = RGBA.from_rgb_n({50*j, 50*i, 255}, 8)
    world.paste(tile.tint(new_color), x, y)
  end
end

StumpyPNG.write(world, "output.png")
```

Note: you might have to delete `libs/` and `shard.lock` to get the branch stuff working,
maybe there is a bug in the `shards` command

**Comment by l3kn** [comment]
I added some of the features into master,
now you can do

```crystal
include StumpyPNG

world = Canvas.new(128, 128)
tile = StumpyPNG.read("base.png")

5.times do |i|
  5.times do |j|
    x = 31 * i
    y = 22 * j
    x -= 16 if j.odd?

    color = RGBA.from_rgb_n({50*j, 50*i, 255}, 8)
    new_tile = tile.map { |pixel| pixel.multiply(color) }
    world.paste(new_tile, x, y)
  end
end

StumpyPNG.write(world, "output.png")
```
